AWSTemplateFormatVersion: '2010-09-09'
Description: SAM Dynamo Test
Resources:
  cfnTestPrices:
    Type: AWS::DynamoDB::GlobalTable
    Properties:
      TableName: cfnTestPrices
      Replicas:
        - us-east-1
        - us-east-2
      AttributeDefinitions:
      - AttributeName: priceId
        AttributeType: S
      - AttributeName: date
        AttributeType: S
      KeySchema:
      - AttributeName: priceId
        KeyType: HASH
      - AttributeName: date
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  cfnTestAggregate:
    Type: AWS::DynamoDB::GlobalTable
    Properties:
      TableName: cfnTestAggregate
      Replicas:
        - us-east-1
        - us-east-2
      AttributeDefinitions:
      - AttributeName: priceType
        AttributeType: S
      KeySchema:
      - AttributeName: priceType
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      StreamSpecification:
        StreamViewType: NEW_IMAGE
