AWSTemplateFormatVersion: '2010-09-09'
Description: Import Changed Table
Resources:
  cfnTestPrices:
    Type: AWS::DynamoDB::GlobalTable
    DeletionPolicy: Retain
    Properties:
      TableName: cfnTestPrices
      Replicas:
        - us-east-2
      AttributeDefinitions:
      - AttributeName: priceId
        AttributeType: S
      - AttributeName: date
        AttributeType: S
      KeySchema:
      - AttributeName: priceId
        KeyType: HASH
      - AttributeName: date
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  TableWriteCapacityScalableTarget:
      Type: AWS::ApplicationAutoScaling::ScalableTarget
      DeletionPolicy: Retain
      Properties:
          MaxCapacity: 100
          MinCapacity: 10
          ResourceId: table/cfnTestPrices
          RoleARN: !GetAtt ScalingRole.Arn
          ScalableDimension: dynamodb:table:WriteCapacityUnits
          ServiceNamespace: dynamodb

  TableWriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DeletionPolicy: Retain
    Properties:
        PolicyName: TableWriteScalingPolicy
        PolicyType: TargetTrackingScaling
        ScalingTargetId: !Ref TableWriteCapacityScalableTarget
        TargetTrackingScalingPolicyConfiguration:
            TargetValue: 70
            ScaleInCooldown: 60
            ScaleOutCooldown: 60
            PredefinedMetricSpecification:
                PredefinedMetricType: DynamoDBWriteCapacityUtilization

  ScalingRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Retain
    Properties:
      RoleName: ScalingRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - application-autoscaling.amazonaws.com
          Action:
            - sts:AssumeRole

  ScalingRolePolicy:
    Type: AWS::IAM::Policy
    DeletionPolicy: Retain
    Properties:
      Roles:
        - !Ref ScalingRole
      PolicyName: ScalingRolePolicyPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - application-autoscaling:*
              - dynamodb:DescribeTable
              - dynamodb:UpdateTable
              - cloudwatch:PutMetricAlarm
              - cloudwatch:DescribeAlarms
              - cloudwatch:GetMetricStatistics
              - cloudwatch:SetAlarmState
              - cloudwatch:DeleteAlarms
            Resource: '*'
