## USAGE: ORDER (6)
## Purpose:
## This cfn adds a replica in us-east-2 - this may take a bit to complete - so we will run this as a change set and execute so it doesn't time out
## Changes:
## - Added Region: us-east-2




AWSTemplateFormatVersion: '2010-09-09'
Description: SAM Dynamo Test
Resources:
  cfnTestPrices:
    Type: AWS::DynamoDB::GlobalTable
    DeletionPolicy: Retain
    Properties:
      TableName: cfnTestPrices
      BillingMode: "PAY_PER_REQUEST"
      Replicas:
        - Region: us-east-1
        - Region: us-east-2
      AttributeDefinitions:
      - AttributeName: priceId
        AttributeType: S
      - AttributeName: date
        AttributeType: S
      KeySchema:
      - AttributeName: priceId
        KeyType: HASH
      - AttributeName: date
        KeyType: RANGE
      StreamSpecification:
            StreamViewType: "NEW_AND_OLD_IMAGES"

  TableWriteCapacityScalableTarget:
      Type: AWS::ApplicationAutoScaling::ScalableTarget
      Properties:
          MaxCapacity: 1000
          MinCapacity: 20
          ResourceId: table/cfnTestPrices
          RoleARN: !GetAtt ScalingRole.Arn
          ScalableDimension: dynamodb:table:WriteCapacityUnits
          ServiceNamespace: dynamodb

  TableWriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
        PolicyName: TableWriteScalingPolicy
        PolicyType: TargetTrackingScaling
        ScalingTargetId: !Ref TableWriteCapacityScalableTarget
        TargetTrackingScalingPolicyConfiguration:
          TargetValue: 75
          ScaleInCooldown: 55
          ScaleOutCooldown: 55
          PredefinedMetricSpecification:
              PredefinedMetricType: DynamoDBWriteCapacityUtilization

  ScalingRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Retain
    Properties:
      RoleName: ScalingRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - application-autoscaling.amazonaws.com
          Action:
            - sts:AssumeRole

  ScalingRolePolicy:
    Type: AWS::IAM::Policy
    DeletionPolicy: Retain
    Properties:
      Roles:
        - !Ref ScalingRole
      PolicyName: ScalingRolePolicyPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - application-autoscaling:*
              - dynamodb:DescribeTable
              - dynamodb:UpdateTable
              - cloudwatch:PutMetricAlarm
              - cloudwatch:DescribeAlarms
              - cloudwatch:GetMetricStatistics
              - cloudwatch:SetAlarmState
              - cloudwatch:DeleteAlarms
            Resource: '*'
