## USAGE: ORDER (2)
## Purpose:
## This CFN protects resources from being deleted when we do a future update.
## It is also preparing the table for the import step as a global table
## Changes:
## - Adding a deltionPolicy: Retain to all resources
## - Adding StreamSpecification to dynamodb to get this table ready for importing
## - Adding BillingMode: PAY_PER_REQUEST - needed for import
## - Adding a Retain true tag
## If you have all these settings - you need to make sure to change something BESIDES the deletionPolicy - this will not trigger a change for cloudformation and another change needs to be present.



AWSTemplateFormatVersion: '2010-09-09'
Description: SAM Dynamo Test
Resources:
  cfnTestPrices:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: cfnTestPrices
      AttributeDefinitions:
      - AttributeName: priceId
        AttributeType: S
      - AttributeName: date
        AttributeType: S
      KeySchema:
      - AttributeName: priceId
        KeyType: HASH
      - AttributeName: date
        KeyType: RANGE
      StreamSpecification:
        StreamViewType: "NEW_AND_OLD_IMAGES"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: Retain
          Value: True

  TableWriteCapacityScalableTarget:
      Type: AWS::ApplicationAutoScaling::ScalableTarget
      DeletionPolicy: Retain
      Properties:
          MaxCapacity: 100
          MinCapacity: 5
          ResourceId: table/cfnTestPrices
          RoleARN: !GetAtt ScalingRole.Arn
          ScalableDimension: dynamodb:table:WriteCapacityUnits
          ServiceNamespace: dynamodb

  TableWriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DeletionPolicy: Retain
    Properties:
        PolicyName: TableWriteScalingPolicy
        PolicyType: TargetTrackingScaling
        ScalingTargetId: !Ref TableWriteCapacityScalableTarget
        TargetTrackingScalingPolicyConfiguration:
            TargetValue: 70
            ScaleInCooldown: 60
            ScaleOutCooldown: 60
            PredefinedMetricSpecification:
                PredefinedMetricType: DynamoDBWriteCapacityUtilization

  ScalingRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Retain
    Properties:
      RoleName: ScalingRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - application-autoscaling.amazonaws.com
          Action:
            - sts:AssumeRole

  ScalingRolePolicy:
    Type: AWS::IAM::Policy
    DeletionPolicy: Retain
    Properties:
      Roles:
        - !Ref ScalingRole
      PolicyName: ScalingRolePolicyPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - application-autoscaling:*
              - dynamodb:DescribeTable
              - dynamodb:UpdateTable
              - cloudwatch:PutMetricAlarm
              - cloudwatch:DescribeAlarms
              - cloudwatch:GetMetricStatistics
              - cloudwatch:SetAlarmState
              - cloudwatch:DeleteAlarms
            Resource: '*'
